version: '3'
services:
  geemap-ws24-run:
    image: geemap-ws24:latest
    env_file:
    - .env
    build: .
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888" 
    volumes:
      - ./notebooks/:/app/notebooks
volumes:
      notebooks: